// <auto-generated />
using System;
using FCanteen.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FCanteen.Data.Migrations
{
    [DbContext(typeof(FCanteenContext))]
    partial class FCanteenContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FCanteen.Data.Entities.DeviceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DeviceLogs");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.MenuItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = "M01",
                            IsAvailable = true,
                            Name = "Món ăn 1",
                            Price = 16000m,
                            Unit = "Phần"
                        },
                        new
                        {
                            Id = "M02",
                            IsAvailable = true,
                            Name = "Món ăn 2",
                            Price = 17000m,
                            Unit = "Phần"
                        },
                        new
                        {
                            Id = "M03",
                            IsAvailable = true,
                            Name = "Món ăn 3",
                            Price = 18000m,
                            Unit = "Phần"
                        },
                        new
                        {
                            Id = "M04",
                            IsAvailable = true,
                            Name = "Món ăn 4",
                            Price = 19000m,
                            Unit = "Phần"
                        },
                        new
                        {
                            Id = "M05",
                            IsAvailable = true,
                            Name = "Món ăn 5",
                            Price = 20000m,
                            Unit = "Phần"
                        },
                        new
                        {
                            Id = "M06",
                            IsAvailable = true,
                            Name = "Món ăn 6",
                            Price = 21000m,
                            Unit = "Phần"
                        },
                        new
                        {
                            Id = "M07",
                            IsAvailable = true,
                            Name = "Món ăn 7",
                            Price = 22000m,
                            Unit = "Phần"
                        },
                        new
                        {
                            Id = "M08",
                            IsAvailable = true,
                            Name = "Món ăn 8",
                            Price = 23000m,
                            Unit = "Phần"
                        },
                        new
                        {
                            Id = "M09",
                            IsAvailable = true,
                            Name = "Món ăn 9",
                            Price = 24000m,
                            Unit = "Phần"
                        },
                        new
                        {
                            Id = "M10",
                            IsAvailable = true,
                            Name = "Món ăn 10",
                            Price = 25000m,
                            Unit = "Phần"
                        },
                        new
                        {
                            Id = "M11",
                            IsAvailable = true,
                            Name = "Món ăn 11",
                            Price = 26000m,
                            Unit = "Phần"
                        },
                        new
                        {
                            Id = "M12",
                            IsAvailable = true,
                            Name = "Món ăn 12",
                            Price = 27000m,
                            Unit = "Phần"
                        },
                        new
                        {
                            Id = "M13",
                            IsAvailable = true,
                            Name = "Món ăn 13",
                            Price = 28000m,
                            Unit = "Phần"
                        },
                        new
                        {
                            Id = "M14",
                            IsAvailable = true,
                            Name = "Món ăn 14",
                            Price = 29000m,
                            Unit = "Phần"
                        },
                        new
                        {
                            Id = "M15",
                            IsAvailable = true,
                            Name = "Món ăn 15",
                            Price = 30000m,
                            Unit = "Phần"
                        });
                });

            modelBuilder.Entity("FCanteen.Data.Entities.OrderTicket", b =>
                {
                    b.Property<string>("TicketId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PosName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("TicketId");

                    b.ToTable("OrderTickets");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.TicketLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MenuItemId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderTicketId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderTicketId");

                    b.ToTable("TicketLines");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.TicketLine", b =>
                {
                    b.HasOne("FCanteen.Data.Entities.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FCanteen.Data.Entities.OrderTicket", "OrderTicket")
                        .WithMany("TicketLines")
                        .HasForeignKey("OrderTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("OrderTicket");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.OrderTicket", b =>
                {
                    b.Navigation("TicketLines");
                });
#pragma warning restore 612, 618
        }
    }
}
